

#' Title
#'
#' @param asca the output of the ASCA_decompose
#' @param npermutations the number of permutations used to construct the null distribution
#' @param quantile the upper quantile of the random variable importance table
#'
#' @return a list with the following item
#' \itemize{
#'  \item{random.varimp.array: }{an array (samples x factors x npermutations) with the random variables importance generated by the ASCA decomposition of permuted data }
#'  \item{upperquantile: }{the upper quantile of the random variable importance}
#'  \item{important.var: }{comparison of the observed variable importance with the upper quantile from the randomised variable importance }
#' }
#' 
#' @details Entries in the important.var item are either "NA" for variables  whose importance is below the upper quantile of randomised data
#' or the actual variable importance values for those > than the randomised variable importance value
#' @export
#'
#' @examples
#' 
#' 
#' 
ASCA_validate.varimp<-function(asca,
                               npermutations=100,
                               quantile=0.95){
  
  shf_varimp <- function(asca){  #internal function to create a shuffle-based varimp
    
    rnd_d <- as.data.frame(lapply(asca$d,sample))
    rnd_asca <- ASCA_decompose(rnd_d,asca$x,asca$f)
    rnd_varimp<-rnd_asca$svds$varimp # the randomised varimp
    return(rnd_varimp)
  }
  rnd_varimparray<- replicate(npermutations, shf_varimp(asca.test.0)) # replicate the shuffle ntimes -> array of random varimp
  
  upperquantile<- apply(rnd_varimparray, c(1,2), function(x) quantile(x,0.95)) # get the upper quant of the varimp table
  obs.varimp<-asca$svds$varimp
  obs.varimp[obs.varimp < upperquantile] <-NA # only show the variable-factor cases where obs varimp > upperquantile random
  
  return=list(random_varimp.array=rnd_varimparray,
              upperquantile= upperquantile,
              important.var=obs.varimp)
}


######



#' Title
#'
#' @param asca the output of ASCA_decompose
#' @param validate.varimp the output of ASCA_validate.varimp
#' @param var the variable [number] to plot
#' @param fact the factor [number] to plot
#'
#' @return an histogram of the random variable importance values and the location of the observed value
#' @export
#'
#' @examples
#' 
plot.validate.varimp<-function(asca, validate.varimp, var, fact){
  hist(validate.varimp$random_varimp.array[var,fact,], breaks = 30, xlim=c(0,1),
       main=substitute(paste("Histogram of ", validate.varimp, sep=", ", "variable ", var, sep="_", "factor ", fact)))
  abline(v=asca$svds$varimp[var,fact], col="red")
}

